services:
  metube:
    container_name: metube
    environment:
      - OUTPUT_TEMPLATE=%(display_id)s.%(ext)s
      - YTDL_OPTIONS={ "format":"bestvideo[vcodec=h264]+bestaudio[ext=m4a]/best[ext=mp4]", "cookiefile":"/cookies/cookies.txt" }
      - DOWNLOAD_DIR=/downloads
    image: ghcr.io/alexta69/metube:latest
    ports:
      - 90:8081
    volumes:
      - .\metube\downloads:/downloads
      - .\metube\cookies:/cookies
    restart: unless-stopped

  calibre-web-automated:
    container_name: calibre-web-automated
    image: crocodilestick/calibre-web-automated:latest
    environment:
      - PUID=1000
      - PGID=100
      - TZ=UTC
      - DOCKER_MODS=lscr.io/linuxserver/mods:universal-calibre-v7.16.0
    volumes:
      - .\calibre-web-automated\config:/config
      - .\calibre-web-automated/ingest:/cwa-book-ingest
      - .\calibre-web-automated/calibre-lib:/calibre-library
      - .\calibre-web-automated/books:/books
    ports:
      - 8084:8083
    restart: unless-stopped
    
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - 8000:8000
      - 9443:9443
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .\portainer_data:/data
