services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      
  metube:
    container_name: metube
    image: ghcr.io/alexta69/metube:latest
    ports:
      - 90:8081
    volumes:
      - /home/arioh/docker/metube/downloads:/downloads
      - /home/arioh/docker/metube/cookies:/cookies
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    volumes:
      - /home/arioh/docker/pgdata:/var/lib/postgresql/data

  linkwarden:
    container_name: linkwarden
    restart: always
    image: ghcr.io/linkwarden/linkwarden:latest
    ports:
      - 100:3000
    volumes:
      - /home/arioh/docker/linkwarden/data:/data/data
    depends_on:
      - postgres
      
  stash:
    image: stashapp/stash:latest
    container_name: stash
    restart: unless-stopped
    ports:
      - 9999:9999
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "2m"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/arioh/docker/stash/config:/root/.stash
      - /home/arioh/docker/stash/data:/data
      - /home/arioh/docker/stash/gallery:/gallery
      - /home/arioh/docker/stash/metadata:/metadata
      - /home/arioh/docker/stash/cache:/cache
      - /home/arioh/docker/stash/blobs:/blobs
      - /home/arioh/docker/stash/generated:/generated
      
  tinymediamanager:
    image: tinymediamanager/tinymediamanager:latest
    container_name: tinymediamanager
    volumes:
      - /home/arioh/docker/tinymediamanager/data:/data
      - /home/arioh/docker/tinymediamanager/media:/media
      - /home/arioh/docker/tinymediamanager/app/addons:/app/addons
    ports:
      - 5900:5900
      - 4000:4000
    restart: unless-stopped

  jdownloader:
    image: jlesage/jdownloader-2
    container_name: jdownloader
    restart: unless-stopped
    ports:
      - 5800:5800
    volumes:
      - /home/arioh/docker/jdownloader/config:/config:rw
      - /home/arioh/docker/jdownloader/downloads:/output:rw
